parameters:
#    env(ELASTICSEARCH_HOST): 'http://elasticsearch:9200'
api_platform:
    title: 'API for kt.team test task'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#    elasticsearch:
#        hosts: ['%env(ELASTICSEARCH_HOST)%']
#        mapping:
#            App\Entity\Task:
#                index: task
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    doctrine:
        enabled: true
