version: '3.7'

services:
  server:
    image: nginx:latest
    restart: always
    volumes:
      - ./public:/var/www/kt_test_task_backend/public
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/var/www/kt_test_task_backend/
    environment:
      APP_ENV: dev
  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - .:/app
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db_user
      POSTGRES_DB: test_db
