version: '3.7'

services:
  server:
    container_name: kt_test_server
    image: nginx:latest
    restart: always
    volumes:
      - ./public:/var/www/kt_test_task_backend/public
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80
    networks:
      - kt_test
  php:
    container_name: kt_test_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/var/www/kt_test_task_backend/
    environment:
      APP_ENV: dev
    networks:
      - kt_test
  composer:
    container_name: kt_test_php_composer
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - .:/app
    networks:
      - kt_test
  db:
    image: postgres:12
    container_name: kt_test_db
    restart: always
    ports:
      - 5499:5432
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db_user
      POSTGRES_DB: test_db
    networks:
      - kt_test
  elastic:
    image: elasticsearch:7.9.1
    container_name: kt_test_elastic01
    environment:
      - node.name=elastic01
      - cluster.name=elastic-docker-cluster
      - discovery.seed_hosts=elastic01
      - cluster.initial_master_nodes=elastic01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elsaticData01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - kt_test
volumes:
  elsaticData01:
    driver: local
networks:
  kt_test:
    driver: bridge
